[package]
name = "webpwk"
version = "0.1.0"
authors = ["Matthew Weeks <scriptjunkie@scriptjunkie.us>"]
edition = "2024"
license = "MIT"

[dependencies]
rouille = "3.6.2"
ed25519-dalek = "2.2.0"
rand = "0.9.2"
hex = "0.4.3"
hmac = "0.12"
sha2 = "0.10"
